/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\flemming.glb 
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import React from "react";

export function Flemming(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/flemming.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Stator"
          geometry={nodes.Stator.geometry}
          material={materials.Iron}
        />
        <mesh
          name="Rotor"
          geometry={nodes.Rotor.geometry}
          material={materials.Alum}
        />
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials.Copper}
          position={[0.66, 0, 0]}
        />
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials.Copper}
          position={[-0.33, 0, -0.572]}
        />
        <mesh
          name="Cylinder002"
          geometry={nodes.Cylinder002.geometry}
          material={materials.Copper}
          position={[-0.33, 0, 0.572]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/flemming.glb");
